//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloWebClient.HelloWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HelloWebService.HelloWebServiceSoap")]
    public interface HelloWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMessage", ReplyAction="*")]
        HelloWebClient.HelloWebService.getMessageResponse getMessage(HelloWebClient.HelloWebService.getMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<HelloWebClient.HelloWebService.getMessageResponse> getMessageAsync(HelloWebClient.HelloWebService.getMessageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMessage", Namespace="http://tempuri.org/", Order=0)]
        public HelloWebClient.HelloWebService.getMessageRequestBody Body;
        
        public getMessageRequest() {
        }
        
        public getMessageRequest(HelloWebClient.HelloWebService.getMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public getMessageRequestBody() {
        }
        
        public getMessageRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public HelloWebClient.HelloWebService.getMessageResponseBody Body;
        
        public getMessageResponse() {
        }
        
        public getMessageResponse(HelloWebClient.HelloWebService.getMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getMessageResult;
        
        public getMessageResponseBody() {
        }
        
        public getMessageResponseBody(string getMessageResult) {
            this.getMessageResult = getMessageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HelloWebServiceSoapChannel : HelloWebClient.HelloWebService.HelloWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloWebServiceSoapClient : System.ServiceModel.ClientBase<HelloWebClient.HelloWebService.HelloWebServiceSoap>, HelloWebClient.HelloWebService.HelloWebServiceSoap {
        
        public HelloWebServiceSoapClient() {
        }
        
        public HelloWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HelloWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HelloWebClient.HelloWebService.getMessageResponse HelloWebClient.HelloWebService.HelloWebServiceSoap.getMessage(HelloWebClient.HelloWebService.getMessageRequest request) {
            return base.Channel.getMessage(request);
        }
        
        public string getMessage(string name) {
            HelloWebClient.HelloWebService.getMessageRequest inValue = new HelloWebClient.HelloWebService.getMessageRequest();
            inValue.Body = new HelloWebClient.HelloWebService.getMessageRequestBody();
            inValue.Body.name = name;
            HelloWebClient.HelloWebService.getMessageResponse retVal = ((HelloWebClient.HelloWebService.HelloWebServiceSoap)(this)).getMessage(inValue);
            return retVal.Body.getMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HelloWebClient.HelloWebService.getMessageResponse> HelloWebClient.HelloWebService.HelloWebServiceSoap.getMessageAsync(HelloWebClient.HelloWebService.getMessageRequest request) {
            return base.Channel.getMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<HelloWebClient.HelloWebService.getMessageResponse> getMessageAsync(string name) {
            HelloWebClient.HelloWebService.getMessageRequest inValue = new HelloWebClient.HelloWebService.getMessageRequest();
            inValue.Body = new HelloWebClient.HelloWebService.getMessageRequestBody();
            inValue.Body.name = name;
            return ((HelloWebClient.HelloWebService.HelloWebServiceSoap)(this)).getMessageAsync(inValue);
        }
    }
}
